//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1



use sea_orm :: entity :: prelude :: * ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq)] # [sea_orm (table_name = "order_item")] pub struct Model { # [sea_orm (primary_key)] pub id : i64 , pub order_id : i64 , pub user_id : String , pub order_sn : String , pub product_id : i64 , pub product_sku_id : i64 , pub product_name : String , pub product_brand : String , pub product_picture : String , pub product_price : Decimal , pub product_quantity : i32 , pub product_attribute : String , pub is_deleted : i16 , pub create_time : DateTime , pub update_time : Option < DateTime > , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { }

impl ActiveModelBehavior for ActiveModel { }