debug = true
# 指定开发环境配置
profile = "development"
[tracing]
log_level = "debug"
[server]
host = "127.0.0.1"
port = 8086
[email]
host = "smtp.qq.com"
port = 587
username = "3108799306@qq.com"
password = "fqaoyqnaxjtsdcjb"
from = "3108799306@qq.com"
reply_to = "3108799306@qq.com"
subject = "锈化动力商城验证码"
[db]
username = "postgres"
password = "root123456"
host = "127.0.0.1"
port = 5_432
database_name = "postgres"

[redis]
host = "127.0.0.1"
port = 6_379
[es]
host = "127.0.0.1"
port = 9_200
[kafka]
brokers = "127.0.0.1:9092"
# 生产者配置
producer = "test"
# 消费者配置
consumer = "test"
