debug = true
# 指定开发环境配置
profile = "development"
[tracing]
log_level = "debug"
[server]
host = "127.0.0.1"
port = 8080
[email]
host = "smtp.qq.com"
port = 587
username = "3108799306@qq.com"
password = "fqaoyqnaxjtsdcjb"
from = "3108799306@qq.com"
reply_to = "3108799306@qq.com"
subject = "锈化动力商城验证码"
[database]
url = "postgres://postgres:root123456@localhost:5432/mgr"
max_connections = 10
min_connections = 1
connect_timeout = 30
idle_timeout = 600

[redis]
mode = "single"
url = "redis://:@localhost:6379"
[es]
host = "127.0.0.1"
port = 9_200
[kafka]
brokers = "127.0.0.1:9092"
[jwt]
jwt_secret = "mgr"
issuer = "http://145632.xyz"
expire = 7200