//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_comment")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub parent_id: Option<i64>,
    pub product_id: Uuid,
    pub product_sku_id: Uuid,
    pub user_id: Uuid,
    pub like_count: Option<i32>,
    pub reply_count: Option<i32>,
    pub star: Option<i32>,
    pub content: Option<String>,
    pub comment_flag: Option<i16>,
    pub hide_flag: Option<i16>,
    pub append_flag: Option<i16>,
    pub resource: Option<String>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub is_deleted: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
