debug = true
# 指定开发环境配置
profile = "development"
[tracing]
log_level = "debug"
[server]
host = "127.0.0.1"
port = 8087
[email]
host = "smtp.qq.com"
port = 587
username = "3108799306@qq.com"
password = "fqaoyqnaxjtsdcjb"
from = "3108799306@qq.com"
reply_to = "3108799306@qq.com"
subject = "锈化动力商城验证码"

[redis]
host = "127.0.0.1"
port = 6_379

[kafka]
brokers = "127.0.0.1:9092"
# 生产者配置
producer = "test"
# 消费者配置
consumer = "test"
