//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "product_spu")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub category_id: i64,
    pub brand_id: String,
    pub name: Option<String>,
    pub product_sn: Option<String>,
    pub pic: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub photo_album: Option<String>,
    pub price: Option<Decimal>,
    pub promotion_price: Option<Decimal>,
    pub promotion_start_time: Option<DateTime>,
    pub promotion_end_time: Option<DateTime>,
    pub sub_title: Option<String>,
    pub sales: Option<i32>,
    pub unit: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub detail: Option<String>,
    pub publish_status: Option<i16>,
    pub new_status: Option<i16>,
    pub recommand_status: Option<i16>,
    pub create_time: Option<DateTime>,
    pub update_time: Option<DateTime>,
    pub is_deleted: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
