//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub avatar: Option<String>,
    pub is_deleted: i16,
    pub is2fa: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
