//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "cart_item")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub product_spu_id: Uuid,
    pub product_sku_id: Uuid,
    pub user_id: Uuid,
    pub product_picture: String,
    pub product_name: String,
    pub product_brand: String,
    pub product_price: Decimal,
    pub product_quantity: i32,
    pub product_attribute: String,
    pub selected: i16,
    pub is_deleted: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
