//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.8

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(unique)]
    pub id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub order_sn: String,
    pub user_id: String,
    pub total_amount: Decimal,
    pub pay_amount: Decimal,
    pub freight_amount: Decimal,
    pub auto_confirm_day: i32,
    pub delivery_company: String,
    pub delivery_sn: String,
    pub delivery_time: DateTime,
    pub receive_name: String,
    pub receive_phone: String,
    pub receive_post_code: String,
    pub receive_province: String,
    pub receive_city: String,
    pub receive_region: String,
    pub receive_detail_address: String,
    pub receive_time: DateTime,
    pub remark: String,
    pub confirm_status: i32,
    pub order_status: i32,
    pub pay_type: i32,
    pub pay_url: String,
    pub pay_time: DateTime,
    pub is_deleted: i16,
    pub create_time: DateTime,
    pub update_time: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
