[package]
authors.workspace = true
edition.workspace = true
name = "router"
publish.workspace = true
version.workspace = true

[dependencies]
api = {path = "../api"}
shared = {path = "../shared"}

axum = {workspace = true}
