[package]
name = "infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
axum={workspace=true}
tokio={workspace=true}
sea-orm={workspace=true}
tracing={workspace=true}
serde={workspace=true}